"""codegen_meta.py — Generate scm_meta.gml + data JSON for runtime loading.

Reads JSON files from gml_scheme/data/meta/ and:
  1. Copies them to build/ for deployment (runtime buffer_load + json_parse)
  2. Generates patricia trie JSON files for tab completion
  3. Generates a small scm_meta.gml that loads everything at runtime

Usage:
    python gml_scheme/codegen_meta.py

Input:  gml_scheme/data/meta/{objects,sprites,sounds,rooms,scripts,functions}.json
        gml_scheme/data/meta/obj_tree.json
Output: gml_scheme/src/scm_meta.gml
        gml_scheme/data/trie/trie_{obj,spr,snd,rm,scr,fn}.json

If data/meta/ does not exist (ExportMeta.csx hasn't been run),
generates an empty stub so the bundle still compiles.
"""

from __future__ import annotations

import json
from pathlib import Path


# ── Patricia trie builder ────────────────────────────────────────


def _build_patricia_trie(names: list[str]) -> dict:
    """Build a compressed (patricia) trie from a sorted list of names.

    Each node is a dict where:
    - Keys are edge labels (substrings, potentially multi-character)
    - Special key "$" marks a terminal (complete name ends here)
    - Values are child nodes (dicts)
    """
    root: dict = {}
    for name in names:
        _patricia_insert(root, name)
    return root


def _patricia_insert(node: dict, word: str) -> None:
    """Insert a word into a patricia trie node."""
    if not word:
        node["$"] = 1
        return

    # Find an existing edge that shares a prefix
    for key in list(node.keys()):
        if key == "$":
            continue
        # Compute shared prefix length
        shared = 0
        while shared < len(key) and shared < len(word) and key[shared] == word[shared]:
            shared += 1

        if shared == 0:
            continue

        if shared == len(key):
            # Edge fully consumed — descend into child
            _patricia_insert(node[key], word[shared:])
            return

        # Partial match — split the edge
        shared_part = key[:shared]
        key_rest = key[shared:]
        word_rest = word[shared:]

        old_child = node.pop(key)
        new_child: dict = {key_rest: old_child}
        if word_rest:
            _patricia_insert(new_child, word_rest)
        else:
            new_child["$"] = 1
        node[shared_part] = new_child
        return

    # No matching edge — create new leaf
    node[word] = {"$": 1}


def _write_json(data: object, out_path: Path) -> int:
    """Write data as pretty-printed JSON. Returns byte size."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(data, indent=2, ensure_ascii=False)
    out_path.write_text(text, encoding="utf-8")
    return len(text)


# ── Namespace config ─────────────────────────────────────────────

# Maps namespace prefix → source JSON filename
_NS_FILES: dict[str, str] = {
    "obj": "objects.json",
    "spr": "sprites.json",
    "snd": "sounds.json",
    "rm": "rooms.json",
    "scr": "scripts.json",
    "fn": "functions.json",
}


# Runtime subfolder for all data files (relative to game directory)
SCM_DATA_DIR = "scm_data"


def generate(meta_dir: Path, out_path: Path) -> None:
    """Generate scm_meta.gml and trie JSON files."""

    trie_dir = meta_dir.parent / "trie"
    trie_dir.mkdir(parents=True, exist_ok=True)

    # Load JSON files (empty arrays if missing)
    def load_json(name: str) -> list[str] | dict:
        p = meta_dir / name
        if p.exists():
            return json.loads(p.read_text(encoding="utf-8"))
        return []

    # Load all namespace arrays
    ns_data: dict[str, list[str]] = {}
    for ns, filename in _NS_FILES.items():
        ns_data[ns] = load_json(filename)  # type: ignore

    # Load obj_tree
    obj_tree: dict[str, list[str]] = load_json("obj_tree.json")  # type: ignore
    if not isinstance(obj_tree, dict):
        obj_tree = {}

    has_data = any(ns_data.values())

    # Build patricia tries → data/trie/
    trie_stats: dict[str, int] = {}
    for ns, names in ns_data.items():
        trie = _build_patricia_trie(names) if names else {}
        size = _write_json(trie, trie_dir / f"trie_{ns}.json")
        trie_stats[ns] = size

    # Stats
    counts = {ns: len(names) for ns, names in ns_data.items()}
    counts["parents"] = len(obj_tree)

    # ── Generate scm_meta.gml ────────────────────────────────────
    lines: list[str] = []
    lines.append("/// scm_meta.gml — Asset metadata for discovery & tab completion")
    lines.append("///")
    lines.append("/// Auto-generated by codegen_meta.py — do not edit.")
    lines.append(f"/// Assets: {counts['obj']} objects, {counts['spr']} sprites, "
                 f"{counts['snd']} sounds, {counts['rm']} rooms, "
                 f"{counts['scr']} scripts, {counts['fn']} functions")
    lines.append("///")
    lines.append("/// All data loaded at runtime via buffer_load + json_parse.")
    lines.append("")

    # Helper to load JSON file
    lines.append("/// Load a JSON file and return the parsed value.")
    lines.append("function scm_meta__load_json(_filename) {")
    lines.append('    var _buf = buffer_load(_filename);')
    lines.append('    var _data = json_parse(buffer_read(_buf, buffer_text));')
    lines.append('    buffer_delete(_buf);')
    lines.append('    return _data;')
    lines.append("}")
    lines.append("")

    # Init function — all runtime loads
    lines.append("/// Initialize asset metadata. Called from scm_init().")
    lines.append("function scm_meta_init() {")

    if has_data:
        lines.append("    // Load asset name arrays")
        for ns, filename in _NS_FILES.items():
            lines.append(f'    global.__scm_meta_{ns} = scm_meta__load_json("{SCM_DATA_DIR}/{filename}");')
        lines.append("")
        lines.append("    // Load object parent→children tree")
        lines.append(f'    global.__scm_meta_obj_tree = scm_meta__load_json("{SCM_DATA_DIR}/obj_tree.json");')
        lines.append("")
        lines.append("    // Load patricia tries for tab completion")
        for ns in ns_data:
            lines.append(f'    global.__scm_trie_{ns} = scm_meta__load_json("{SCM_DATA_DIR}/trie_{ns}.json");')
    else:
        lines.append("    // No metadata available — empty stubs")
        for ns in ns_data:
            lines.append(f"    global.__scm_meta_{ns} = [];")
        lines.append("    global.__scm_meta_obj_tree = {};")
        for ns in ns_data:
            lines.append(f"    global.__scm_trie_{ns} = {{}};")

    lines.append("}")
    lines.append("")

    # ── Trie walk ────────────────────────────────────────────────
    lines.append("/// Walk a patricia trie to find the node matching a prefix.")
    lines.append("/// Returns the subtrie at _suffix, or undefined if no match.")
    lines.append("function scm_meta_trie_walk(_trie, _suffix) {")
    lines.append("    var _node = _trie;")
    lines.append("    var _pos = 1;")
    lines.append("    var _slen = string_length(_suffix);")
    lines.append("    while (_pos <= _slen) {")
    lines.append("        var _found = false;")
    lines.append("        var _keys = variable_struct_get_names(_node);")
    lines.append("        for (var _i = 0; _i < array_length(_keys); _i++) {")
    lines.append('            var _edge = _keys[_i];')
    lines.append('            if (_edge == "$") continue;')
    lines.append("            var _elen = string_length(_edge);")
    lines.append("            var _remaining = _slen - _pos + 1;")
    lines.append("            if (_elen <= _remaining) {")
    lines.append("                if (string_copy(_suffix, _pos, _elen) == _edge) {")
    lines.append("                    _node = _node[$ _edge];")
    lines.append("                    _pos += _elen;")
    lines.append("                    _found = true;")
    lines.append("                    break;")
    lines.append("                }")
    lines.append("            } else {")
    lines.append("                if (string_copy(_edge, 1, _remaining) == string_copy(_suffix, _pos, _remaining)) {")
    lines.append("                    var _rest = string_copy(_edge, _remaining + 1, _elen - _remaining);")
    lines.append("                    var _child = _node[$ _edge];")
    lines.append("                    var _synth = {};")
    lines.append("                    _synth[$ _rest] = _child;")
    lines.append("                    return _synth;")
    lines.append("                }")
    lines.append("            }")
    lines.append("        }")
    lines.append("        if (!_found) return undefined;")
    lines.append("    }")
    lines.append("    return _node;")
    lines.append("}")
    lines.append("")

    # ── Trie collect ─────────────────────────────────────────────
    lines.append("/// Collect all completions from a trie node, prepending _prefix to each.")
    lines.append("/// Returns array of full completion strings.")
    lines.append("function scm_meta_trie_collect(_node, _prefix, _max_results) {")
    lines.append("    var _results = [];")
    lines.append("    var _stack = [[_node, _prefix]];")
    lines.append("    while (array_length(_stack) > 0) {")
    lines.append("        var _top = array_pop(_stack);")
    lines.append("        var _n = _top[0], _p = _top[1];")
    lines.append('        if (variable_struct_exists(_n, "$")) {')
    lines.append("            array_push(_results, _p);")
    lines.append("            if (array_length(_results) >= _max_results) return _results;")
    lines.append("        }")
    lines.append("        var _keys = variable_struct_get_names(_n);")
    lines.append("        for (var _i = array_length(_keys) - 1; _i >= 0; _i--) {")
    lines.append('            if (_keys[_i] == "$") continue;')
    lines.append("            array_push(_stack, [_n[$ _keys[_i]], _p + _keys[_i]]);")
    lines.append("        }")
    lines.append("    }")
    lines.append("    return _results;")
    lines.append("}")
    lines.append("")

    # ── Trie getter ──────────────────────────────────────────────
    lines.append("/// Get trie for a namespace prefix. Returns undefined for unknown ns.")
    lines.append("function scm_meta_get_trie(_ns) {")
    lines.append("    switch (_ns) {")
    for ns in ns_data:
        pad = " " if len(ns) < 3 else ""
        lines.append(f'        case "{ns}":{pad} return global.__scm_trie_{ns};')
    lines.append("        default: return undefined;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # ── Array-based prefixed names (for search-names) ────────────
    lines.append("/// Get all names for a namespace prefix (array-based, for search-names).")
    lines.append('/// Returns a GML array of strings like ["obj:o_player", ...].')
    lines.append("function scm_meta_prefixed_names(_prefix) {")
    lines.append("    var _arr;")
    lines.append("    switch (_prefix) {")
    for ns in ns_data:
        pad = " " if len(ns) < 3 else ""
        lines.append(f'        case "{ns}":{pad} _arr = global.__scm_meta_{ns}; break;')
    lines.append("        default: return [];")
    lines.append("    }")
    lines.append('    var _result = [];')
    lines.append("    var _n = array_length(_arr);")
    lines.append("    for (var _i = 0; _i < _n; _i++) {")
    lines.append('        array_push(_result, _prefix + ":" + _arr[_i]);')
    lines.append("    }")
    lines.append("    return _result;")
    lines.append("}")
    lines.append("")

    # Write output
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    status = "with data" if has_data else "STUB (no meta JSON found)"
    trie_sizes = ", ".join(f"{ns}={s // 1024}KB" for ns, s in trie_stats.items())
    print(
        f"Generated scm_meta.gml {status} → {out_path}"
        f" ({counts['obj']}o {counts['spr']}s "
        f"{counts['snd']}snd {counts['rm']}r "
        f"{counts['scr']}scr {counts['fn']}fn)"
    )
    print(f"  Tries → {trie_dir}/ ({trie_sizes})")


def main() -> None:
    here = Path(__file__).parent
    meta_dir = here / "data" / "meta"
    out_path = here / "src" / "scm_meta.gml"
    generate(meta_dir, out_path)


if __name__ == "__main__":
    main()
