/// scm_bridge.gml — Game bridge: hand-written FFI functions
///
/// Contains functions that require custom logic beyond mechanical
/// unwrap-call-wrap (e.g. typeof, debug-log, ds_map/struct iteration).
///
/// Mechanical 1:1 GML builtin wrappers live in scm_gml_builtins.gml
/// (auto-generated by codegen_builtins.py). This includes gml:method
/// and gml:self which, despite runtime context, are expressible as
/// plain template wrappers.
///
/// Register with scm_register_bridge(_env).

// ═══════════════════════════════════════════════════════════════════
//  Composite functions (require GML-specific loops / sentinels)
// ═══════════════════════════════════════════════════════════════════

/// (ds-list->list list_id) → Scheme list
function scm_bi_ds_list_to_list(_args) {
    var _ds = scm_unwrap(_args.car);
    var _sz = ds_list_size(_ds);
    var _result = scm_nil();
    for (var _i = _sz - 1; _i >= 0; _i--) {
        _result = scm_cons(scm_wrap(ds_list_find_value(_ds, _i)), _result);
    }
    return _result;
}

/// (array->list arr) — convert GML array to Scheme list (shallow wrap)
function scm_bi_array_to_list(_args) {
    var _arr = scm_unwrap(_args.car);
    var _result = scm_nil();
    for (var _i = array_length(_arr) - 1; _i >= 0; _i--) {
        _result = scm_cons(scm_wrap(_arr[_i]), _result);
    }
    return _result;
}

// ═══════════════════════════════════════════════════════════════════
//  Utility
// ═══════════════════════════════════════════════════════════════════

/// (debug-log arg1 arg2 ...) — variadic, write to GameMaker debug console
function scm_bi_debug_log(_args) {
    var _msg = "";
    while (_args.t == SCM_PAIR) {
        _msg += scm_display_str(_args.car);
        _args = _args.cdr;
    }
    show_debug_message("[scm] " + _msg);
    return scm_void();
}

/// (typeof val) — return type name as string
function scm_bi_typeof(_args) {
    switch (_args.car.t) {
        case SCM_NIL:    return scm_str("nil");
        case SCM_BOOL:   return scm_str("boolean");
        case SCM_NUM:    return scm_str("number");
        case SCM_STR:    return scm_str("string");
        case SCM_SYM:    return scm_str("symbol");
        case SCM_PAIR:   return scm_str("pair");
        case SCM_FN:     return scm_str("builtin");
        case SCM_LAMBDA: return scm_str("lambda");
        case SCM_VOID:   return scm_str("void");
        case SCM_ERR:    return scm_str("error");
        case SCM_HANDLE:
            switch (_args.car.ht) {
                case SCM_HT_ARRAY:    return scm_str("array");
                case SCM_HT_STRUCT:   return scm_str("struct");
                case SCM_HT_METHOD:   return scm_str("method");
                default:              return scm_str("handle");
            }
        default:         return scm_str("unknown");
    }
}

// ═════════════════════════════════════════════════════════════════
//  Handle predicates
// ═════════════════════════════════════════════════════════════════

// Only array? and struct? are reliable — GML can detect these at runtime.
// ds_map/ds_list/instance IDs are plain numbers and cannot be distinguished
// from other numbers without risking false positives.
function scm_bi_is_handle(_args)   { return scm_bool(_args.car.t == SCM_HANDLE); }
function scm_bi_is_array(_args)    { return scm_bool(_args.car.t == SCM_HANDLE && _args.car.ht == SCM_HT_ARRAY); }
function scm_bi_is_struct(_args)   { return scm_bool(_args.car.t == SCM_HANDLE && _args.car.ht == SCM_HT_STRUCT); }
function scm_bi_is_method(_args)   { return scm_bool(_args.car.t == SCM_HANDLE && _args.car.ht == SCM_HT_METHOD); }

// ═════════════════════════════════════════════════════════════════
//  Struct construction
// ═════════════════════════════════════════════════════════════════

/// (make-struct) → empty GML struct {}
function scm_bi_make_struct(_args) {
    return scm_handle({}, SCM_HT_STRUCT);
}

/// (alist->struct alist) → GML struct from ((key . val) ...) pairs
function scm_bi_alist_to_struct(_args) {
    var _lst = _args.car;
    var _s = {};
    var _p = _lst;
    while (_p.t == SCM_PAIR) {
        var _pair = _p.car;
        if (_pair.t != SCM_PAIR)
            return scm_err("alist->struct: expected pair, got " + scm__type_name(_pair.t));
        var _k = scm_unwrap(_pair.car);
        var _v = scm_deep_unwrap(_pair.cdr);
        variable_struct_set(_s, _k, _v);
        _p = _p.cdr;
    }
    return scm_handle(_s, SCM_HT_STRUCT);
}

// ═════════════════════════════════════════════════════════════════
//  Deep conversion
// ═════════════════════════════════════════════════════════════════

/// (list->array lst) — recursively convert Scheme list to GML array
function scm_bi_list_to_array(_args) {
    var _lst = _args.car;
    if (_lst.t == SCM_NIL) return scm_handle([], SCM_HT_ARRAY);
    if (_lst.t != SCM_PAIR) return scm_err("list->array: expected list, got " + scm__type_name(_lst.t));
    var _arr = [];
    var _p = _lst;
    while (_p.t == SCM_PAIR) {
        array_push(_arr, scm_deep_unwrap(_p.car));
        _p = _p.cdr;
    }
    return scm_handle(_arr, SCM_HT_ARRAY);
}

/// (proc->method proc) — convert Scheme procedure to GML callable (method)
/// The returned closure keeps `self` free for rebinding via gml:method.
function scm_bi_proc_to_method(_args) {
    var _proc = _args.car;
    if (_proc.t != SCM_FN && _proc.t != SCM_LAMBDA)
        return scm_err("proc->method: expected procedure, got " + scm__type_name(_proc.t));
    return scm_handle(scm__proc_to_method(_proc), SCM_HT_METHOD);
}

// ═══════════════════════════════════════════════════════════════════
//  Registration
// ═══════════════════════════════════════════════════════════════════

function scm_register_bridge(_env) {
    // Constants (values, not functions — cannot be in codegen)
    scm_env_set(_env, "gml:noone",         scm_num(noone));

    // Composite functions (iterating)
    scm_env_set(_env, "ds-list->list",     scm_fn("ds-list->list",     scm_bi_ds_list_to_list));
    scm_env_set(_env, "array->list",       scm_fn("array->list",       scm_bi_array_to_list));

    // Utility
    scm_env_set(_env, "debug-log",         scm_fn("debug-log",         scm_bi_debug_log));
    scm_env_set(_env, "typeof",            scm_fn("typeof",            scm_bi_typeof));

    // Handle predicates
    scm_env_set(_env, "handle?",           scm_fn("handle?",           scm_bi_is_handle));
    scm_env_set(_env, "array?",            scm_fn("array?",            scm_bi_is_array));
    scm_env_set(_env, "struct?",           scm_fn("struct?",           scm_bi_is_struct));
    scm_env_set(_env, "method?",           scm_fn("method?",           scm_bi_is_method));

    // Struct construction
    scm_env_set(_env, "make-struct",       scm_fn("make-struct",       scm_bi_make_struct));
    scm_env_set(_env, "alist->struct",     scm_fn("alist->struct",     scm_bi_alist_to_struct));

    // Deep conversion
    scm_env_set(_env, "list->array",       scm_fn("list->array",       scm_bi_list_to_array));
    scm_env_set(_env, "proc->method",      scm_fn("proc->method",      scm_bi_proc_to_method));
}
