/// scm_bridge.gml — Hand-written FFI requiring SCM internals
///
/// Only ffi:proc->method remains here — it needs .t, scm__proc_to_method,
/// scm_handle(), which cannot be expressed in pure Scheme.
///
/// Everything else has been moved:
///   type-of, handle?, make-struct    → deleted (redundant)
///   array?, struct?, method?         → stdlib.scm (aliases for gml:is-*)
///   array, struct, alist->struct     → stdlib.scm (pure Scheme)
///   list->array                      → stdlib.scm (pure Scheme, shallow)
///   inspect, inspect-instance,
///   inspect-ds-map, inspect-ds-list  → stdlib.scm (pure Scheme)
///   apropos (was env-find)           → scm_core.gml
///   %self-test (was self-test)       → scm_core.gml
///   noone                            → stdlib.scm (define noone -4)
///   debug-log                        → deleted
///   log                              → stdlib.scm
///
/// Mechanical 1:1 GML builtin wrappers live in scm_gml_builtins.gml
/// (auto-generated by codegen_builtins.py).
///
/// Register with scm_register_bridge(_env).

// ═══════════════════════════════════════════════════════════════════
//  FFI — Scheme↔GML type boundary
// ═══════════════════════════════════════════════════════════════════

/// (ffi:proc->method proc) — convert Scheme procedure to GML callable (method)
/// The returned closure keeps `self` free for rebinding via gml:method.
function scm_bi_proc_to_method(_args) {
    var _proc = _args.car;
    if (_proc.t != SCM_FN && _proc.t != SCM_LAMBDA && _proc.t != SCM_CASE_LAMBDA)
        return scm_err("ffi:proc->method: expected procedure, got " + scm__type_name(_proc.t));
    return scm_handle(scm__proc_to_method(_proc), SCM_HT_METHOD);
}

// ═══════════════════════════════════════════════════════════════════
//  Registration
// ═══════════════════════════════════════════════════════════════════

function scm_register_bridge(_env) {
    scm_env_set(_env, "ffi:proc->method", scm_fn("ffi:proc->method", scm_bi_proc_to_method));
}
