/// scm_bridge.gml — Game bridge: hand-written FFI functions
///
/// Contains functions that require custom logic beyond mechanical
/// unwrap-call-wrap (e.g. typeof, debug-log, ds_map/struct iteration).
///
/// Mechanical 1:1 GML builtin wrappers live in scm_gml_builtins.gml
/// (auto-generated by codegen_builtins.py). This includes gml:method
/// and gml:self which, despite runtime context, are expressible as
/// plain template wrappers.
///
/// Register with scm_register_bridge(_env).

// ═══════════════════════════════════════════════════════════════════
//  Composite functions (require GML-specific loops / sentinels)
// ═══════════════════════════════════════════════════════════════════

/// (ds-list->list list_id) → Scheme list
function scm_bi_ds_list_to_list(_args) {
    var _ds = scm_unwrap(_args.car);
    var _sz = ds_list_size(_ds);
    var _result = scm_nil();
    for (var _i = _sz - 1; _i >= 0; _i--) {
        _result = scm_cons(scm_wrap(ds_list_find_value(_ds, _i)), _result);
    }
    return _result;
}

/// (array->list arr) — convert GML array to Scheme list (shallow wrap)
function scm_bi_array_to_list(_args) {
    var _arr = scm_unwrap(_args.car);
    var _result = scm_nil();
    for (var _i = array_length(_arr) - 1; _i >= 0; _i--) {
        _result = scm_cons(scm_wrap(_arr[_i]), _result);
    }
    return _result;
}

// ═══════════════════════════════════════════════════════════════════
//  Utility
// ═══════════════════════════════════════════════════════════════════

/// (debug-log arg1 arg2 ...) — variadic, write to GameMaker debug console
function scm_bi_debug_log(_args) {
    var _msg = "";
    while (_args.t == SCM_PAIR) {
        _msg += scm_display_str(_args.car);
        _args = _args.cdr;
    }
    show_debug_message("[scm] " + _msg);
    return scm_void();
}

/// (gml:script-execute script_index arg...) — variadic, call legacy script
function scm_bi_script_execute(_args) {
    if (_args.t != SCM_PAIR) return scm_err("gml:script-execute: expected at least 1 argument (script index)");
    var _idx = scm_unwrap(_args.car);
    _args = _args.cdr;
    // Collect remaining args into a temporary array
    var _arr = [];
    while (_args.t == SCM_PAIR) {
        array_push(_arr, scm_unwrap(_args.car));
        _args = _args.cdr;
    }
    return scm_wrap(script_execute_ext(_idx, _arr));
}

/// (typeof val) — return type name as string
function scm_bi_typeof(_args) {
    switch (_args.car.t) {
        case SCM_NIL:    return scm_str("nil");
        case SCM_BOOL:   return scm_str("boolean");
        case SCM_NUM:    return scm_str("number");
        case SCM_STR:    return scm_str("string");
        case SCM_SYM:    return scm_str("symbol");
        case SCM_PAIR:   return scm_str("pair");
        case SCM_FN:     return scm_str("builtin");
        case SCM_LAMBDA: return scm_str("lambda");
        case SCM_VOID:   return scm_str("void");
        case SCM_ERR:    return scm_str("error");
        case SCM_HANDLE:
            switch (_args.car.ht) {
                case SCM_HT_ARRAY:    return scm_str("array");
                case SCM_HT_STRUCT:   return scm_str("struct");
                case SCM_HT_METHOD:   return scm_str("method");
                default:              return scm_str("handle");
            }
        default:         return scm_str("unknown");
    }
}

// ═════════════════════════════════════════════════════════════════
//  Handle predicates
// ═════════════════════════════════════════════════════════════════

// Only array? and struct? are reliable — GML can detect these at runtime.
// ds_map/ds_list/instance IDs are plain numbers and cannot be distinguished
// from other numbers without risking false positives.
function scm_bi_is_handle(_args)   { return scm_bool(_args.car.t == SCM_HANDLE); }
function scm_bi_is_array(_args)    { return scm_bool(_args.car.t == SCM_HANDLE && _args.car.ht == SCM_HT_ARRAY); }
function scm_bi_is_struct(_args)   { return scm_bool(_args.car.t == SCM_HANDLE && _args.car.ht == SCM_HT_STRUCT); }
function scm_bi_is_method(_args)   { return scm_bool(_args.car.t == SCM_HANDLE && _args.car.ht == SCM_HT_METHOD); }

// ═════════════════════════════════════════════════════════════════
//  Struct construction
// ═════════════════════════════════════════════════════════════════

/// (make-struct) → empty GML struct {}
function scm_bi_make_struct(_args) {
    return scm_handle({}, SCM_HT_STRUCT);
}

/// (array arg ...) → GML array from arguments (variadic)
function scm_bi_array(_args) {
    var _arr = [];
    var _p = _args;
    while (_p.t == SCM_PAIR) {
        array_push(_arr, scm_unwrap(_p.car));
        _p = _p.cdr;
    }
    return scm_handle(_arr, SCM_HT_ARRAY);
}

/// (struct key val ...) → GML struct from key-value pairs (variadic)
function scm_bi_struct(_args) {
    var _s = {};
    var _p = _args;
    while (_p.t == SCM_PAIR) {
        var _k = scm_unwrap(_p.car);
        _p = _p.cdr;
        if (_p.t != SCM_PAIR) return scm_err("struct: odd number of arguments (missing value for key " + string(_k) + ")");
        var _v = scm_unwrap(_p.car);
        _p = _p.cdr;
        variable_struct_set(_s, _k, _v);
    }
    return scm_handle(_s, SCM_HT_STRUCT);
}

/// (alist->struct alist) → GML struct from ((key . val) ...) pairs
function scm_bi_alist_to_struct(_args) {
    var _lst = _args.car;
    var _s = {};
    var _p = _lst;
    while (_p.t == SCM_PAIR) {
        var _pair = _p.car;
        if (_pair.t != SCM_PAIR)
            return scm_err("alist->struct: expected pair, got " + scm__type_name(_pair.t));
        var _k = scm_unwrap(_pair.car);
        var _v = scm_deep_unwrap(_pair.cdr);
        variable_struct_set(_s, _k, _v);
        _p = _p.cdr;
    }
    return scm_handle(_s, SCM_HT_STRUCT);
}

// ═════════════════════════════════════════════════════════════════
//  Deep conversion
// ═════════════════════════════════════════════════════════════════

/// (list->array lst) — recursively convert Scheme list to GML array
function scm_bi_list_to_array(_args) {
    var _lst = _args.car;
    if (_lst.t == SCM_NIL) return scm_handle([], SCM_HT_ARRAY);
    if (_lst.t != SCM_PAIR) return scm_err("list->array: expected list, got " + scm__type_name(_lst.t));
    var _arr = [];
    var _p = _lst;
    while (_p.t == SCM_PAIR) {
        array_push(_arr, scm_deep_unwrap(_p.car));
        _p = _p.cdr;
    }
    return scm_handle(_arr, SCM_HT_ARRAY);
}

/// (proc->method proc) — convert Scheme procedure to GML callable (method)
/// The returned closure keeps `self` free for rebinding via gml:method.
function scm_bi_proc_to_method(_args) {
    var _proc = _args.car;
    if (_proc.t != SCM_FN && _proc.t != SCM_LAMBDA)
        return scm_err("proc->method: expected procedure, got " + scm__type_name(_proc.t));
    return scm_handle(scm__proc_to_method(_proc), SCM_HT_METHOD);
}

// ═══════════════════════════════════════════════════════════════════
//  Environment introspection
// ═══════════════════════════════════════════════════════════════════

/// (env-find pattern) → list of (name . type-string) for bindings containing pattern
/// pattern is matched as substring (case-insensitive).
function scm_bi_env_find(_args) {
    var _pattern = scm_unwrap(_args.car);
    var _pat_lower = string_lower(_pattern);
    var _env = global.scm_env;
    var _seen = ds_map_create();
    var _result = scm_nil();

    while (_env != undefined) {
        var _keys = variable_struct_get_names(_env.bindings);
        for (var _i = 0; _i < array_length(_keys); _i++) {
            var _k = _keys[_i];
            if (!ds_map_exists(_seen, _k)) {
                ds_map_set(_seen, _k, true);
                if (string_pos(_pat_lower, string_lower(_k)) > 0) {
                    var _val = variable_struct_get(_env.bindings, _k);
                    var _type_name;
                    switch (_val.t) {
                        case SCM_FN:     _type_name = "builtin"; break;
                        case SCM_LAMBDA: _type_name = "lambda"; break;
                        case SCM_NUM:    _type_name = "number"; break;
                        case SCM_STR:    _type_name = "string"; break;
                        case SCM_BOOL:   _type_name = "boolean"; break;
                        case SCM_PAIR:   _type_name = "pair"; break;
                        case SCM_NIL:    _type_name = "nil"; break;
                        case SCM_HANDLE: _type_name = "handle"; break;
                        default:         _type_name = "other"; break;
                    }
                    _result = scm_cons(
                        scm_cons(scm_str(_k), scm_str(_type_name)),
                        _result
                    );
                }
            }
        }
        _env = _env.parent;
    }
    ds_map_destroy(_seen);
    return _result;
}

// ═══════════════════════════════════════════════════════════════════
// ═══════════════════════════════════════════════════════════════════
//  Self-test (smoke test for REPL)
// ═══════════════════════════════════════════════════════════════════

/// (self-test) — run interpreter smoke tests, return result summary
function scm_bi_self_test(_args) {
    scm_trace("[self-test] starting smoke tests");
    var _tests = [
        ["(+ 1 2 3)", "6"],
        ["(* 2 3 4)", "24"],
        ["(- 10 3)", "7"],
        ["(/ 10 2)", "5"],
        ["(if #t 'yes 'no)", "yes"],
        ["(if #f 'yes 'no)", "no"],
        ["(car '(1 2 3))", "1"],
        ["(cdr '(1 2 3))", "(2 3)"],
        ["(length '(a b c))", "3"],
        ["(map (lambda (x) (* x x)) '(1 2 3))", "(1 4 9)"],
        ["(filter (lambda (x) (> x 2)) '(1 2 3 4 5))", "(3 4 5)"],
        ["(let ((x 10) (y 20)) (+ x y))", "30"],
        ["(let loop ((n 5) (acc 1)) (if (= n 0) acc (loop (- n 1) (* acc n))))", "120"],
        ["(define (fact n) (if (<= n 1) 1 (* n (fact (- n 1))))) (fact 10)", "3628800"],  // 2-expr program
        ["(string-append \"hello\" \" \" \"world\")", "\"hello world\""],
        ["(equal? '(1 2 3) '(1 2 3))", "#t"],
        ["(car 5)", "#<error:"],
        ["(cdr \"hello\")", "#<error:"],
        ["(+ 1 \"a\")", "#<error:"],
        ["(abs #f)", "#<error:"],
        ["(modulo \"a\" 2)", "#<error:"],
        ["((lambda (x) x) 1 2)", "#<error:"],
        ["((lambda (x y) x) 1)", "#<error:"],
        // guard
        ["(guard (e (#t (string-append \"caught: \" e))) (car 5))", "\"caught: car: expected pair, got number\""],
        ["(guard (e (#t 'ok)) (+ 1 2))", "3"],
    ];

    var _pass = 0;
    var _fail = 0;

    for (var _i = 0; _i < array_length(_tests); _i++) {
        var _input    = _tests[_i][0];
        var _expected = _tests[_i][1];
        var _actual;
        try {
            var _result = scm_eval_program(_input, global.scm_env);
            _actual = scm_write_str(_result);
        } catch (_e) {
            _actual = "#<gml-crash: " + string(_e) + ">";
        }
        var _match = false;
        if (string_pos("#<error:", _expected) == 1) {
            _match = (string_pos("#<error:", _actual) == 1);
        } else {
            _match = (_actual == _expected);
        }
        if (_match) {
            _pass++;
            scm_output_write("  ok  #" + string(_i) + " " + _input + "\n");
        } else {
            _fail++;
            scm_output_write("  FAIL #" + string(_i) + " " + _input + "\n");
            scm_output_write("       got:      " + _actual + "\n");
            scm_output_write("       expected: " + _expected + "\n");
        }
    }

    var _summary = string(_pass) + "/" + string(_pass + _fail) + " passed";
    if (_fail > 0) {
        _summary += ", " + string(_fail) + " FAILED";
    }
    scm_output_write(_summary + "\n");
    scm_trace("[self-test] " + _summary);
    return scm_void();
}

// ═══════════════════════════════════════════════════════════════════
//  Registration
// ═══════════════════════════════════════════════════════════════════

function scm_register_bridge(_env) {
    // Constants (values, not functions — cannot be in codegen)
    scm_env_set(_env, "gml:noone",         scm_num(noone));

    // Composite functions (iterating)
    scm_env_set(_env, "ds-list->list",     scm_fn("ds-list->list",     scm_bi_ds_list_to_list));
    scm_env_set(_env, "array->list",       scm_fn("array->list",       scm_bi_array_to_list));

    // Script execution (variadic — not expressible in codegen)
    scm_env_set(_env, "gml:script-execute", scm_fn("gml:script-execute", scm_bi_script_execute));

    // Utility
    scm_env_set(_env, "debug-log",         scm_fn("debug-log",         scm_bi_debug_log));
    scm_env_set(_env, "typeof",            scm_fn("typeof",            scm_bi_typeof));

    // Handle predicates
    scm_env_set(_env, "handle?",           scm_fn("handle?",           scm_bi_is_handle));
    scm_env_set(_env, "array?",            scm_fn("array?",            scm_bi_is_array));
    scm_env_set(_env, "struct?",           scm_fn("struct?",           scm_bi_is_struct));
    scm_env_set(_env, "method?",           scm_fn("method?",           scm_bi_is_method));

    // Struct construction
    scm_env_set(_env, "make-struct",       scm_fn("make-struct",       scm_bi_make_struct));
    scm_env_set(_env, "array",             scm_fn("array",             scm_bi_array));
    scm_env_set(_env, "struct",            scm_fn("struct",            scm_bi_struct));
    scm_env_set(_env, "alist->struct",     scm_fn("alist->struct",     scm_bi_alist_to_struct));

    // Environment introspection
    scm_env_set(_env, "env-find",          scm_fn("env-find",          scm_bi_env_find));

    // Deep conversion
    scm_env_set(_env, "list->array",       scm_fn("list->array",       scm_bi_list_to_array));
    scm_env_set(_env, "proc->method",      scm_fn("proc->method",      scm_bi_proc_to_method));

    // Self-test
    scm_env_set(_env, "self-test",         scm_fn("self-test",         scm_bi_self_test));
}
